### ISSUE TITLE
DB_NAME not found

### ISSUE THREAD

**Issue by Dleau** [othmbela/fifa-21-api#1]
Hi, there. This is a cool project. I'm getting this traceback when attempting `python3 manage.py makemigrations`. Thoughts?

> Traceback (most recent call last):
>   File "manage.py", line 22, in <module>
>     main()
>   File "manage.py", line 18, in main
>     execute_from_command_line(sys.argv)
>   File "/home/dillon/Downloads/fifa-21-api/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
>     utility.execute()
>   File "/home/dillon/Downloads/fifa-21-api/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 345, in execute
>     settings.INSTALLED_APPS
>   File "/home/dillon/Downloads/fifa-21-api/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 82, in __getattr__
>     self._setup(name)
>   File "/home/dillon/Downloads/fifa-21-api/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 69, in _setup
>     self._wrapped = Settings(settings_module)
>   File "/home/dillon/Downloads/fifa-21-api/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 170, in __init__
>     mod = importlib.import_module(self.SETTINGS_MODULE)
>   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/home/dillon/Downloads/fifa-21-api/settings/settings.py", line 90, in <module>
>     'NAME': config('DB_NAME'),
>   File "/home/dillon/Downloads/fifa-21-api/venv/lib/python3.7/site-packages/decouple.py", line 199, in __call__
>     return self.config(*args, **kwargs)
>   File "/home/dillon/Downloads/fifa-21-api/venv/lib/python3.7/site-packages/decouple.py", line 83, in __call__
>     return self.get(*args, **kwargs)
>   File "/home/dillon/Downloads/fifa-21-api/venv/lib/python3.7/site-packages/decouple.py", line 68, in get
>     raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
> decouple.UndefinedValueError: DB_NAME not found. Declare it as envvar or define a default value.

**Comment by othmbela** [comment]
Hey,

It seems that you need to create a .env file with the credentials of your database (you can find an example with the .env.example file). 

Also, do you have postgresql installed on your local machine ?

Please let me know if you've any other issue/question.
